name: Runes
version: ${project.version}
main: passcraft.runes.Runes
authors: [Enrypase]
description: Runes in minecraft! :O
  commands:
    reload:
      description: reloads the reading of YML file.
      usage: /<command>
    getRune:
      description: gets a specified rune.
      usage: /<command>
    getRunes:
      description: get all the runes read in the YML file.
      usage: /<command>
    shutdown:
      description: shuts down the plugin.
      usage: /<command>